flags: {}
packages:
- '.'
- location:
    git: https://github.com/cauterize-tools/cauterize.git
    commit: 348b07492a87218a428b6753e05f2f1ded0e0106
- location:
    git: https://github.com/cauterize-tools/crucible.git
    commit: ed603e7f8eb68b9ffcf8a402b51116b1465ca7ec
extra-deps:
  - s-cargot-0.1.0.0
resolver: lts-2.21
